# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: grid

optimized_metric: "val/mean_R1"

hydra:
  mode: "MULTIRUN"

  job:
    env_set:
      WANDB_RUN_GROUP: "${oc.select:hydra.sweeper.study_name, 'mamba_grid'}"

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: sqlite:///mamba_grid.db
    study_name: mamba_grid_dstate_lr
    n_jobs: 1
    direction: maximize
    n_trials: 6
    
    params:      
      model.text_net.d_state: choice(32, 64)           
      model.optimizer.lr: choice(0.00015, 0.00018, 0.00022)

      model.image_net.d_model: choice(512)
      data.max_length: 128
      model.text_net.dropout: 0.2
      trainer.accumulate_grad_batches: 4
      seed: 12345