_target_: src.models.mamba3_module.Mamba3LitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4            # 0.0001 # was 10x smaller
  weight_decay: 0.1

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max  # Since we want to maximize recall metrics
  factor: 0.1
  patience: 10

# scheduler:
#  _target_: transformers.get_cosine_schedule_with_warmup
#  _partial_: true
#  num_warmup_steps: 100  # Adjust based on your steps/epoch
#  num_training_steps: 4000 # Total steps for your run


image_net:
  _target_: src.models.components.vit_custom_multiscale_augmentation.ViTOnlySimpleOptimized
  backbone: vit_b32
  pretrained: true
  d_model: 256
  freeze_backbone: false  # Fine-tune for faster adaptation, unfreezes just last 4 layers
  use_layer_norm: true
  dropout: 0.3

text_net:
  _target_: src.models.components.mamba_ssm_local.modules.mamba3.Mamba3
  d_model: 256
  d_state: 32
  d_conv: 4
  expand: 2
  headdim: 16
  dropout: 0.3

# compile model for faster training with pytorch 2.0
compile: false

logit_scale_init: 0.07  # Tune this between 0.01 and 0.2