defaults:
  - text_net: mamba3
  - _self_

_target_: src.models.mamba3_module.Mamba3LitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00015              # 0.0001 # was 10x smaller
  weight_decay: 0.05

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max 
  factor: 0.1
  patience: 5

image_net:
  _target_: src.models.components.vit_custom_multiscale_augmentation.ViTOnlySimpleOptimized
  backbone: vit_b32
  pretrained: true
  d_model: 512 # TODO: 512
  freeze_backbone: false  # Fine-tune for faster adaptation, unfreezes just last 4 layers
  use_layer_norm: true
  dropout: 0.2 


# compile model for faster training with pytorch 2.0
compile: false

logit_scale_init: 0.07  # Tune this between 0.01 and 0.2
